= 🛳️ Onboarding

IMPORTANT: If you are onboarding, it's your job to update this list with anything you notice we forgot!

NOTE: This would be used for onboarding new engineers to the team--getting access to various softwares, email groups, slack channels, etc. But, since this is just for me, I will use it as my onboarding checklist when I get a new computer to get it set up how I like.

* [ ] Update OS
* [ ] Go to settings to
** [ ] Enable two-finger tap ‘right click’
** [ ] Increase track pad speed
* [ ] Install XCode
** [ ] More particularly: https://developer.apple.com/download/all/?q=command%20line[Command Line Tools]
* [ ] Install Spark Email Client
* [ ] Browser Setup (Perhaps install https://zen-browser.app/[Zen Browser])
** [ ] Install Bitwarden
** [ ] Search: DuckDuckGo
** [ ] Advanced: Show full website address
** [ ] Advanced: Show features for web developers
** [ ] View: Show Status bar (for links on hover)
* [ ] Install Terminal Emulator (https://ghostty.org/[Ghostty])
* [ ] Install https://brew.sh/[homebrew]
* [ ] Install `lazygit` (https://github.com/jesseduffield/lazygit[repo])
** [ ] `brew install lazygit`
* [ ] Install https://github.com/tmux/tmux/wiki[tmux]
** [ ] `brew install tmux`
* [ ] Get `git` set up https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent[with ssh] to GitHub
** [ ] https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent[Create new SSH key] and https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account[add it] to the github account
** [ ] Also https://docs.gitlab.com/user/ssh/[add to to GitLab]
* [ ] Install https://www.nerdfonts.com[NerdFonts]
** [ ] I’ve liked FiraCode and GoMono before…
** [ ] Add it to your terminal(s) preferences
* [ ] Install https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating[nvm (node version manager)] BEFORE adding any .zprofile, .bashrc, .zshrc, etc. (it will try to automatically add a script to a dotfile if it's there, but we take car of that in our config later).
* [ ] Install Nvim
** [ ] Homebrew is an option, as discussed https://github.com/neovim/neovim/blob/master/INSTALL.md[on the Install page]
** [ ] Install `ripgrep` for https://github.com/trogers1/kickstart.nvim?tab=readme-ov-file#install-external-dependencies[the kickstart config]:
*** `brew install ripgrep`
** Download/install golang/cargo for nvim AI plugin: https://go.dev/doc/install
* Clone my https://github.com/trogers1/config[config repo]
** Inside, run the 'setup' script as described in the README.
** [ ] Run `nvm install --lts` to get the latest node version installed (should now be in the path after setup)
** [ ] Start `nvim` to install all plugins (make sure `nvm` is installed and `node` has been installed globally first or the ts/js/prettier/css language servers will fail to install; same for `cargo` with golang and my avante-with-permissions plugin)
** [ ] Install any LSP requirements that I want (Golang, terraform, etc.)
* [ ] Grab My `.zprofile` from GitHub and move to `~`
* [ ] Grab the rest of my config from GitHub and run the setup scripts.
* [ ] Install Browsers
** [ ] Firefox
** [ ] Chrome
* [ ] Install VS Code and maybe Cursor
** [ ] Sync settings by signing in with GitHub
* [ ] Probably some docker solution (Rancher Desktop or Colima?)
* [ ]  SQL Interfaces
** [ ]  pgAdmin
** [ ]  Beekeeper
* [ ]  Http Requester
** [ ]  Bruno
* [ ]  Install `opencode` via homebrew
** [ ]  Add API tokens
*** [ ]  DeepSeek
* [ ] Fix macOS key repeat silliness https://superuser.com/questions/363252/how-to-enable-keyboard-repeat-on-a-mac[as described here]
** `defaults write -g ApplePressAndHoldEnabled -bool false` (turn off the press+hold feature)
** `defaults write NSGlobalDomain KeyRepeat -int 0` (set repeat speed to be as fast as it will allow)
** (optional) `defaults write NSGlobalDomain InitialKeyRepeat -int NUMBER` (set how soon it starts repeating after a press)
*** Where NUMBER is an integer around 7 or so with smaller numbers being a faster transition to repeating.

== Probably

* [ ] Spotify (or just use the browser and pin the tab so you can actually close it)
* [ ] VPN of some sort
** [ ] Mullvad

== IDE Extensions (VSCode)

=== Required

* https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode[Prettier]
* https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint[ESLint]
* https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens[Error Lens]
* https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner[Snyk Security]

=== Recommended

* https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform[Terraform]
* https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens[Git Lens]
* https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer[Live Server]
* https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker[Code Spell Checker]

== macOS

A unix-like environment is helpful, but you'll still need to install some things such as

* install `homebrew`
* install `nvm` with homebrew
* install docker and cogima/Rancher Desktop
* Install browsers


== Windows

I’ll need a Unix-like dev environment to develop. I am not a fan of Windows nor am I super familiar with it, so everything takes me much longer to figure out. 

To get Windows to be as much like a Unix-like system as possible, the most appropriate option is probably the Windows Subsystem for Linux (WSL). To set up WSL, I’ll https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview[need to install it], which can be done via a command prompt (either `Powershell` or `cmd`). Generally, you can just use a command like

`wsl --install ubuntu`

This will install the Ubuntu subsystem.

From there, you should be able to see a "Ubuntu" startup item in your Start Menu. You can use this to launch a WSL2 terminal.

From there, you should use `git` to clone one of the team's repositories into the directory of your choosing (this will likely require you to create an SSH key).

From there, you can `cd` into the folder that was just created (you can use `ls` to view the file structure and see the folder you just created) and then use `code .` to open VS Code in WSL2. This will properly link your subsystem's file system with VS Code.

If you successfully linked WSL2, you should see this in the lower-left corner of your VS Code instance.

Linking the WSL2 file system with VS Code properly is very important! If you attempt to open the repository from within Windows itself, simple actions such as `yarn install` will take much longer to complete than normal.
